### ISSUE TITLE
ClientAsync does not work in GTK mainloop

### ISSUE THREAD

**Issue by DaKnig** [Siriusmart/invidious-rs#2]
when trying to get `ClientAsync::default().popular()` future to process inside GTK mainloop (not based on tokio), it complains about there not being a tokio reactor active.
there are runtimes outside tokio, please support them, or document that requirement.

**Comment by Siriusmart** [comment]
Ok I see what went wrong, the default crate used to send http requests in `ClientAsync` is reqwest, that thing only supports tokio runtime and nothing else. Technically this crate does not care if you have a tokio runtime or not, its just the dependencies of the crate requiring it.

I will turn everything into a trait in the future, so that you can just add your own fetch method in case non of the current fetch methods support that runtime.

---

I've done some testing with `async-std`, and by using the featurn `isahc_async` instead of `reqwest_async`, i can make it work in `async-std`, assuming that tokio and async-std are not the only two runtimes isahc support, it might work in the gtk mainloop.

If you remove `reqwest_async` and add `isahc_async`, your code wont need to change because then isahc will be the only async fetch method, and becomes default.

Hope that works
