### ISSUE TITLE
use Instant in Video and friends

### ISSUE THREAD

**Issue by DaKnig** [Siriusmart/invidious-rs#7]
instead of seconds since 1970, use time::Instant, more useful...

**Comment by Siriusmart** [comment]
By time::Instant do you mean how long since the time of publishing?

Because this crate simply use the invidious api, for example [this video](https://vid.puffyan.us/api/v1/videos/aircAruvnKk) (use firefox dev tools so you can actually see the json).

You can see we are only provided the timestamp of publish (second since 1970), so thats what the struct is showing.

---

If you want to know the time since the video's public, use `chrono::Utc::now().timestamp() - video_publish_timestamp` instead.

Did I get what you're saying correctly?

**Comment by DaKnig** [comment]
std::time::Instant is a struct that represents "point in time", timestamp of publish is "point in time" :) would like you to convert it to std::time::Instant since then I as a user can use that as *time* and not as *u64* - u64 does not tell me what this is. ofc I know its seconds since 1970... but if you want to convey that better, use `std::time::Instant` to show a point in time.

I can then , for example, know the `std::time::Duration` by `std::time::now().elapsed(published)` or so

**Comment by Siriusmart** [comment]
no srsly, you need to understand that this crate is not supposed to do anything fancy. it just returns whatever the invidious api responded it and that's all.

maybe someone else can make another higher level crate which wraps on this crate, i dont really care. but i've made this for my other project youtube-tui, and i'm keeping the maintenance effort to the bare minimum, so while I will be fixing errors and adding missing fields, i wont be actively adding any new features to the crate, i hope you understand.

if you would like to have Instant instead of a u64, you can have a function on your end for that. but if you want a `Duration` instead you should use `Duration::from_secs()`
